-- Base de datos de prueba
-- MySQL Connection: testdb
-- Schema: test

DROP TABLE IF EXISTS ORDERS_APP;
DROP TABLE IF EXISTS USERS_APP;

CREATE TABLE USERS_APP (
    user_id DECIMAL(5,0) NOT NULL,
    firstname VARCHAR(20) DEFAULT NULL,
    lastname VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (user_id)
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE ORDERS_APP (
    order_id DECIMAL(5,0) NOT NULL,
    user_id DECIMAL(5,0) NOT NULL,
    country VARCHAR(25) DEFAULT NULL,
    PRIMARY KEY (order_id),
    KEY user_id_idx (user_id),
    CONSTRAINT `order-user` FOREIGN KEY (user_id)
        REFERENCES USERS_APP (user_id)
        ON DELETE CASCADE ON UPDATE CASCADE
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;

